/*
Copyright 2024 Blnk Finance Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package blnk

import (
	"context"
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha512"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/segmentio/kafka-go"
	"github.com/sirupsen/logrus"

	"github.com/blnkfinance/blnk/model"
)

// RedactedSecretPlaceholder is what a SubscriberSecret renders as, in every form.
const RedactedSecretPlaceholder = "[REDACTED]"

// SubscriberSecret carries a generated SCRAM password in a form that cannot be printed,
// logged or serialised by accident.
type SubscriberSecret struct {
	// value is the plaintext. Unexported so that no other package can read it, and
	// deliberately not tagged: no tag is needed because the marshallers below are what
	// encoding/json consults.
	value string
}

// NewSubscriberSecret wraps a generated password.
//
// Parameters:
//   - password string: the plaintext, generated by the subscriber service.
//
// Returns:
//   - SubscriberSecret: a value that renders as RedactedSecretPlaceholder everywhere.
func NewSubscriberSecret(password string) SubscriberSecret {
	return SubscriberSecret{value: password}
}

// IsZero reports whether no secret is held. Used by validation, which must distinguish
// "absent" from "present but unusable" without reading the value.
func (s SubscriberSecret) IsZero() bool {
	return s.value == ""
}

// Len returns the secret's length in bytes.
func (s SubscriberSecret) Len() int {
	return len(s.value)
}

// String renders the placeholder, so a Stringer-aware caller cannot print the secret.
func (s SubscriberSecret) String() string {
	return RedactedSecretPlaceholder
}

// GoString renders the placeholder for %#v, which would otherwise print the struct
// literal including the unexported field's contents.
func (s SubscriberSecret) GoString() string {
	return "SubscriberSecret(" + RedactedSecretPlaceholder + ")"
}

// Format renders the placeholder for every fmt verb.
func (s SubscriberSecret) Format(state fmt.State, _ rune) {
	_, _ = state.Write([]byte(RedactedSecretPlaceholder))
}

// MarshalJSON renders the placeholder as a JSON string.
func (s SubscriberSecret) MarshalJSON() ([]byte, error) {
	return []byte(`"` + RedactedSecretPlaceholder + `"`), nil
}

// MarshalText renders the placeholder, covering encoding.TextMarshaler consumers.
func (s SubscriberSecret) MarshalText() ([]byte, error) {
	return []byte(RedactedSecretPlaceholder), nil
}

// reveal returns the plaintext. Unexported by design: only this package derives from it.
func (s SubscriberSecret) reveal() string {
	return s.value
}

// SubscriberProvisioningRequest is everything needed to turn a registry row into a real
// Kafka access boundary: one SCRAM credential plus a set of ACL bindings.
type SubscriberProvisioningRequest struct {
	// SubscriberID is the registry business key, carried for log correlation only. It
	// takes no part in the credential or the ACLs.
	SubscriberID string

	// Principal is the SASL/SCRAM username, which is the subscriber's Kafka principal
	// (model.EventSubscriber.KafkaPrincipal). Required.
	Principal string

	// Password is the generated secret. Required, and restricted to printable ASCII — see
	// validateSCRAMPassword for why that restriction is a correctness requirement rather
	// than a policy preference.
	Password SubscriberSecret

	// ConsumerGroupPrefix is the consumer group namespace the subscriber is granted Read
	// on, bound with a PREFIXED pattern so every group whose name starts with it is
	// covered. Normally the subscriber's consumer group ID. When empty, no group binding
	// is created and the subscriber cannot join a group at all, which is reported as a
	// warning.
	ConsumerGroupPrefix string

	// Topics is the exact set of topics the credential may read
	// (model.EventSubscriber.AuthorizedTopics). Each is bound with a LITERAL pattern. An
	// empty set is legitimate and means the principal can read nothing — the fail-closed
	// default of a freshly registered subscriber — and is reported as a warning rather
	// than silently widened.
	Topics []string

	// Iterations is the PBKDF2 iteration count. Zero selects DefaultScramIterations, and
	// any value below MinScramIterations is raised to it because the broker would
	// otherwise reject the credential outright.
	Iterations int

	// Host restricts the binding to one client host. Empty selects ACLHostAny, which is
	// the right default for subscribers on networks Blnk does not control.
	Host string

	// KeyScoped says that the registry row this request was built from declares a
	// partition-key prefix, and therefore that RECORD-LEVEL READ MUST BE WITHHELD.
	KeyScoped bool

	// DeferCompensation asks provisioning to REPORT a needed compensation instead of
	// performing it.
	DeferCompensation bool

	// DeclaredKeyScope carries the partition key prefix the REGISTRY ROW records, for the
	// sole purpose of CHECKING KeyScoped against the row it claims to come from. It is
	// never turned into a binding, because there is no binding to turn it into.
	DeclaredKeyScope string
}

// NewSubscriberProvisioningRequest maps a registry row and a freshly generated password
// onto a provisioning request.
//
// Parameters:
//   - subscriber *model.EventSubscriber: the registry row.
//   - password string: the generated secret, owned and returned once by the subscriber
//     service.
//
// Returns:
//   - SubscriberProvisioningRequest: ready to pass to ProvisionSubscriberPrincipal.
func NewSubscriberProvisioningRequest(subscriber *model.EventSubscriber, password string) SubscriberProvisioningRequest {
	if subscriber == nil {
		return SubscriberProvisioningRequest{Password: NewSubscriberSecret(password)}
	}

	return SubscriberProvisioningRequest{
		SubscriberID:        subscriber.SubscriberID,
		Principal:           subscriber.KafkaPrincipal,
		Password:            NewSubscriberSecret(password),
		ConsumerGroupPrefix: subscriber.ConsumerGroupID,
		Topics:              subscriber.AuthorizedTopics,
		// Read from the SAME row as the topics, so a grant can never be built with one
		// subscriber's topic list and another's enforcement decision.
		KeyScoped: subscriber.RequiresGatewayDelivery(),
		// The prefix itself travels beside the flag it decided, for no purpose other than
		// letting validate confirm the two agree. Every binding is derived from KeyScoped;
		// nothing reads this value to grant anything.
		DeclaredKeyScope: subscriber.RequestedKeyScope(),
	}
}

// SubscriberProvisioningResult reports what was provisioned, for the caller's log line,
// response and tests.
type SubscriberProvisioningResult struct {
	// SubscriberID echoes the request, for correlation.
	SubscriberID string

	// Principal is the principal the credential belongs to.
	Principal string

	// Mechanism is always SubscriberSASLMechanism.
	Mechanism string

	// Iterations is the PBKDF2 iteration count actually used, after the minimum was
	// applied.
	Iterations int

	// Topics is the normalised topic set the credential was granted Read and Describe
	// on.
	Topics []string

	// ConsumerGroupPrefix is the group namespace granted Read, empty when none was
	// requested.
	ConsumerGroupPrefix string

	// ACLBindings is how many bindings the subscriber's authorization implies, and so how
	// many the broker holds for it after a successful provisioning.
	ACLBindings int

	// ACLBindingsRemoved is how many OBSOLETE Blnk-owned bindings reconciliation deleted:
	ACLBindingsRemoved int

	// ForeignACLBindings is how many bindings on this principal Blnk does not provision
	// and deliberately did not touch — a hand-made grant, a DENY, a Write.
	ForeignACLBindings int

	// CompensationOwed reports that provisioning failed after the credential was written
	// and that the caller asked for the compensation to be DEFERRED, so it has not run.
	CompensationOwed bool

	// OwedBindings are the bindings the failed provisioning attempted, so a deferred
	// compensation deletes exactly those rather than everything the principal holds.
	OwedBindings []kafka.ACLEntry

	// ForeignACLBindingsGranting is how many of those foreign bindings GRANT access rather
	// than restricting it.
	ForeignACLBindingsGranting int

	// CredentialReplaced is true when the principal already held a SCRAM credential and
	// this call replaced it. Re-issuing is a supported operation, not an error, and this
	// flag is how an operator sees that an existing consumer's credential just stopped
	// working.
	CredentialReplaced bool

	// AuthorizerActive reports whether the broker confirmed that it enforces ACLs.
	AuthorizerActive bool

	// TopicRecordAccessGranted reports whether the bindings written include Read on the
	// subscriber's topics — that is, whether this principal may fetch records DIRECTLY
	// from the broker.
	TopicRecordAccessGranted bool

	// KeyScopeBoundaryVerified reports that a key-scoped subscriber's partition-key
	// boundary was CONFIRMED to be enforceable before this result was returned.
	KeyScopeBoundaryVerified bool

	// CredentialWritten reports whether a SCRAM credential is believed to exist at the
	// broker when this result was returned.
	CredentialWritten bool

	// Compensated reports that provisioning failed after the credential was written and
	// that the credential was then successfully revoked.
	Compensated bool

	// ProvisionedAt is when provisioning completed.
	ProvisionedAt time.Time
}

// ProvisionSubscriberPrincipal creates or replaces a subscriber's SCRAM credential and
// binds the ACLs that are its access boundary.
//
// Parameters:
//   - ctx context.Context: honoured before every round trip.
//   - req SubscriberProvisioningRequest: the boundary to provision.
//
// Returns:
//   - SubscriberProvisioningResult: partially populated when an error is returned, so a
//     caller can tell whether the credential was written before the bindings failed.
//   - error: ErrKafkaAdminNotConfigured, a validation error, or a wrapped broker error.
func (a *KafkaAdminClient) ProvisionSubscriberPrincipal(
	ctx context.Context,
	req SubscriberProvisioningRequest,
) (_ SubscriberProvisioningResult, err error) {
	ctx, span := startKafkaAdminSpan(ctx, "provision_subscriber_principal",
		hashedSubscriberSpanAttribute(req.SubscriberID))
	defer span.End()
	defer func() { failKafkaAdminSpan(span, err) }()

	result := SubscriberProvisioningResult{
		SubscriberID: strings.TrimSpace(req.SubscriberID),
		Mechanism:    SubscriberSASLMechanism,
	}

	if err := a.ready(ctx); err != nil {
		return result, err
	}

	if err := req.validate(); err != nil {
		return result, err
	}

	// THE PERMIT IS TAKEN HERE, before the first round trip and therefore before anything
	// this call could be left holding exists. A refusal at this line is a clean refusal:
	// no credential at the broker, no binding, no obligation for the settlement processor
	// to carry. That ordering is the whole point — the alternative, which is what an
	// unbounded admin client produces, is a request that runs out of budget three round
	// trips in, having already written the credential it can no longer authorise.
	ctx, releasePermit, err := a.admitAdminConversation(ctx, kafkaAdminForward)
	if err != nil {
		return result, err
	}

	defer releasePermit()

	principal := req.principal()
	iterations := req.iterations()
	topics := req.normalizedTopics()
	groupPrefix := req.consumerGroupPrefix()

	result.Principal = principal
	result.Iterations = iterations
	result.Topics = topics
	result.ConsumerGroupPrefix = groupPrefix

	// THE RESERVED-PRINCIPAL GATE, because a collision here means the SCRAM upsert below
	// would rotate one of this
	// deployment's OWN credentials and return it in the response. Configuration validation
	// already refuses such a deployment at start-up; this is the second gate, because
	// configuration can be reloaded and an admin client can be constructed from a
	// configuration this process never validated. It costs one slice comparison and it is
	// the difference between an authorized API call minting a subscriber credential and an
	// authorized API call minting a Kafka superuser one.
	if err := a.requirePrincipalNotReserved(principal); err != nil {
		return result, err
	}

	// BEFORE anything is written. A credential minted against a broker that does not
	// enforce ACLs — or one whose enforcement cannot be confirmed — has no boundary, so
	// this is a precondition rather than a diagnostic.
	if err := a.requireEnforcedAuthorizer(ctx, principal); err != nil {
		return result, err
	}
	result.AuthorizerActive = true

	// Informational only: the upsert below works whether or not a credential exists, so a
	// probe failure that is not a cancellation must not stop provisioning.
	existed, err := a.SubscriberCredentialExists(ctx, principal)
	switch {
	case err == nil:
		result.CredentialReplaced = existed
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return result, err
	default:
		logrus.WithFields(logrus.Fields{
			"principal_hash": subscriberLogLabel(principal),
			"error_class":    kafkaErrorClassField("provision_subscriber_principal", err),
		}).Debug(
			"kafka admin: could not determine whether the principal already holds a credential; provisioning anyway",
		)
	}

	upsertion, err := deriveScramUpsertion(principal, req.Password.reveal(), iterations)
	if err != nil {
		return result, err
	}

	writeOutcome, err := a.upsertScramCredential(ctx, upsertion)

	// SET FROM WHAT IS KNOWN, not from whether the call returned an error. An indeterminate
	// write may have landed, and the flag is what every downstream decision reads: whether
	// to compensate, whether to file a settlement obligation, and what the failure log says
	// the broker was left holding. Treating unknown as nothing is what left principals at
	// the broker that nothing afterwards could find.
	result.CredentialWritten = writeOutcome.mayHaveReachedTheBroker()

	if err != nil {
		if writeOutcome == scramWriteRejected {
			// The broker refused, so nothing exists to undo and the caller's own error is the
			// whole story.
			return result, err
		}

		// The credential may be live with no boundary at all, which is the same state the ACL
		// failure below produces and is compensated the same way. Logged here because this is
		// the one branch whose cause is an ABSENCE of information, and an operator reading the
		// revocation that follows should be able to see why it was attempted.
		logrus.WithFields(logrus.Fields{
			"principal_hash":     subscriberLogLabel(principal),
			"subscriber_id_hash": subscriberLogLabel(result.SubscriberID),
			"error_class":        kafkaErrorClassField("provision_subscriber_principal", err),
		}).Warn(
			"kafka admin: the SCRAM credential write got no usable answer, so the credential may be " +
				"live at the broker with no authorization boundary; it is being revoked as though it " +
				"landed, because the safe reading of an unknown write is that it did",
		)

		if req.DeferCompensation {
			result.CompensationOwed = true
			result.OwedBindings = req.aclEntries()

			return result, err
		}

		if cleanupErr := a.compensateFailedProvisioning(ctx, principal, req.aclEntries()); cleanupErr == nil {
			result.CredentialWritten = false
			result.Compensated = true
		}

		return result, err
	}

	// RECONCILED, not merely created. The broker's Blnk-owned bindings for this principal
	// are made exactly what the row's authorization implies, so a topic removed from
	// authorized_topics since the last issuance has its Read and Describe bindings DELETED
	// here. Creating without deleting made a subscriber's broker-side grant the union of
	// every authorization it had ever held: narrowing the registry left the old access
	// live, and revocation could not find it either, because revocation derives what to
	// delete from the row that no longer names the topic.
	bindings := req.aclEntries()

	reconciliation, err := a.reconcileSubscriberACLs(ctx, principal, bindings)

	// A refusal here takes the compensation path below, so the credential just written is
	// revoked. Verifying after the response would be verifying nothing: the secret would
	// already be in the caller's hands.
	if err == nil {
		err = verifyKeyScopeBoundary(req, bindings, reconciliation, result.AuthorizerActive)
	}

	if err != nil {
		// the credential exists and its boundary does not. That combination is the one state
		// provisioning must never leave behind, because the principal can authenticate — so
		// it is compensated by revoking the credential before returning.
		if req.DeferCompensation {
			result.CompensationOwed = true
			result.OwedBindings = bindings

			return result, err
		}

		if cleanupErr := a.compensateFailedProvisioning(ctx, principal, bindings); cleanupErr == nil {
			result.CredentialWritten = false
			result.Compensated = true
		}

		return result, err
	}

	result.ACLBindings = len(bindings)
	result.ACLBindingsRemoved = reconciliation.Removed
	// Read back off the bindings that were actually reconciled, not off the request, so the
	// result describes the grant the broker now holds.
	result.TopicRecordAccessGranted = bindingsGrantTopicRead(bindings)
	// True only for a key-scoped request, and by this line the verification above has already
	// passed — provisioning refuses rather than reaching here unverified.
	result.KeyScopeBoundaryVerified = req.KeyScoped
	// Deny bindings only. A foreign ALLOW made reconcileSubscriberACLs return an error
	// above, so a successful provisioning is by construction one with no widening binding
	// on the principal — which is what makes the issuance response's enforced-access
	// declaration true rather than aspirational.
	result.ForeignACLBindings = len(reconciliation.Foreign())

	if len(topics) == 0 {
		logrus.WithFields(logrus.Fields{
			"principal_hash":     subscriberLogLabel(principal),
			"subscriber_id_hash": subscriberLogLabel(result.SubscriberID),
		}).Warn(
			"kafka admin: principal provisioned with no authorised topics, so it can read nothing. This is the " +
				"fail-closed default of a newly registered subscriber; grant topics on the subscriber before " +
				"issuing credentials it is expected to consume with",
		)
	}

	if groupPrefix == "" {
		logrus.WithFields(logrus.Fields{
			"principal_hash":     subscriberLogLabel(principal),
			"subscriber_id_hash": subscriberLogLabel(result.SubscriberID),
		}).Warn(
			"kafka admin: principal provisioned without a consumer group grant, so it cannot join a consumer " +
				"group; set the subscriber's consumer group before issuing credentials",
		)
	}

	result.ProvisionedAt = time.Now().UTC()

	logrus.WithFields(logrus.Fields{
		"subscriber_id_hash":   subscriberLogLabel(result.SubscriberID),
		"principal_hash":       subscriberLogLabel(principal),
		"mechanism":            SubscriberSASLMechanism,
		"iterations":           iterations,
		"topics":               len(topics),
		"consumer_group_hash":  consumerGroupLogLabel(groupPrefix),
		"acl_bindings":         result.ACLBindings,
		"acl_bindings_removed": result.ACLBindingsRemoved,
		"foreign_acl_bindings": result.ForeignACLBindings,
		"foreign_acl_granting": result.ForeignACLBindingsGranting,
		"credential_replaced":  result.CredentialReplaced,
		"authorizer_active":    result.AuthorizerActive,
	}).Info("kafka admin: subscriber principal provisioned")

	return result, nil
}

// validate rejects a request that cannot produce a usable credential, or that asks for
// a boundary this service will not grant.
func (r SubscriberProvisioningRequest) validate() error {
	subscriberID := strings.TrimSpace(r.SubscriberID)
	if subscriberID == "" {
		return errors.New(
			"kafka admin: a subscriber id is required to provision a credential; the principal and " +
				"consumer group namespace are derived from it and cannot be taken from the request",
		)
	}

	expectedPrincipal, err := model.CanonicalKafkaPrincipal(subscriberID)
	if err != nil {
		return fmt.Errorf("kafka admin: cannot derive a Kafka principal for this subscriber: %w", err)
	}

	// Compared EXACTLY, not after trimming. The values are quoted so a whitespace-only
	// difference is visible in the message.
	if r.Principal != expectedPrincipal {
		return fmt.Errorf(
			"kafka admin: refusing to provision principal %q for subscriber %q; the only principal "+
				"this subscriber may hold is %q, derived from its identifier. A principal supplied by a "+
				"caller is a request for an access boundary, not for a name",
			r.Principal, subscriberID, expectedPrincipal,
		)
	}

	expectedNamespace, err := model.CanonicalConsumerGroupNamespace(subscriberID)
	if err != nil {
		return fmt.Errorf("kafka admin: cannot derive a consumer group namespace for this subscriber: %w", err)
	}

	// The request carries the subscriber's consumer group, which must be a leaf INSIDE its
	// own namespace. The prefixed binding is then made over the namespace, never over the
	// supplied string, so a group chosen to overlap a sibling's namespace cannot be
	// granted.
	if group := strings.TrimSpace(r.ConsumerGroupPrefix); group != "" &&
		!model.IsInSubscriberGroupNamespace(group, expectedNamespace) {
		return fmt.Errorf(
			"kafka admin: refusing to grant consumer group %q to subscriber %q; it lies outside the "+
				"subscriber's own namespace %q, and a prefixed grant on it would reach another "+
				"subscriber's groups",
			group, subscriberID, expectedNamespace,
		)
	}

	if err := r.validateTopics(); err != nil {
		return err
	}

	if err := r.validateHost(); err != nil {
		return err
	}

	if err := r.validateKeyScope(); err != nil {
		return err
	}

	return validateSCRAMPassword(r.Password.reveal())
}

// validateKeyScope refuses a request that declares a key scope it does not narrow the
// grant for.
func (r SubscriberProvisioningRequest) validateKeyScope() error {
	scope := strings.TrimSpace(r.DeclaredKeyScope)
	if scope == "" || r.KeyScoped {
		return nil
	}

	return fmt.Errorf(
		"kafka admin: refusing to provision subscriber %q, whose registry row records the partition "+
			"key prefix %q while this request asks for the ordinary grant; Kafka's authorizer has no "+
			"message-key dimension, so the credential would hold Read on every record of every "+
			"authorised topic and the registry would describe a narrower boundary than exists. Build "+
			"the request with NewSubscriberProvisioningRequest, which withholds record-level Read for "+
			"a key-scoped row, or clear the prefix to accept whole-topic access",
		strings.TrimSpace(r.SubscriberID), scope,
	)
}

// validateTopics refuses any topic outside the subscriber-grantable allowlist.
func (r SubscriberProvisioningRequest) validateTopics() error {
	for _, topic := range normalizeTopicList(r.Topics) {
		if !IsSubscriberGrantableTopic(topic) {
			if IsSubscriberPrivilegedTopic(topic) {
				return fmt.Errorf(
					"kafka admin: refusing to grant the internal category topic %q; it carries Blnk's "+
						"own error text verbatim and every event type the catalogue does not yet "+
						"recognise, so it is grantable only where the deployment has acknowledged that "+
						"by setting KAFKA_SUBSCRIBER_INTERNAL_TOPIC_ACCESS. Set it, or grant only the "+
						"tenant category topics (%s)",
					topic, strings.Join(SubscriberGrantableTopics(), ", "),
				)
			}

			return fmt.Errorf(
				"kafka admin: refusing to grant topic %q; only Blnk-owned category topics may be "+
					"granted (%s). Dead-letter topics carry other subscribers' failed events together "+
					"with Blnk's failure metadata and have no subscriber audience",
				topic, strings.Join(SubscriberGrantableTopics(), ", "),
			)
		}

		if IsSubscriberPrivilegedTopic(topic) {
			logrus.WithFields(logrus.Fields{
				"subscriber_id_hash": hashLogIdentifier(strings.TrimSpace(r.SubscriberID)),
				"topic":              topic,
			}).Warn(
				"kafka admin: granting the internal category topic to a subscriber, which this " +
					"deployment has acknowledged with KAFKA_SUBSCRIBER_INTERNAL_TOPIC_ACCESS. The " +
					"principal will read Blnk's own error text verbatim, for the whole deployment, " +
					"plus every event type the catalogue does not yet recognise",
			)
		}
	}

	return nil
}

// validateHost refuses a host pattern that is neither the explicit any-host wildcard
// nor a plausible single host.
func (r SubscriberProvisioningRequest) validateHost() error {
	host := strings.TrimSpace(r.Host)
	if host == "" || host == ACLHostAny {
		return nil
	}

	for i := 0; i < len(host); i++ {
		if character := host[i]; character < '!' || character > '~' ||
			character == '*' || character == '?' || character == ',' {
			return fmt.Errorf(
				"kafka admin: refusing ACL host %q; a host restriction must be a single host, or %q "+
					"to allow any host. Wildcards, separators and non-printable characters are not accepted",
				host, ACLHostAny,
			)
		}
	}

	return nil
}

// principal returns the trimmed SASL username as SUPPLIED.
func (r SubscriberProvisioningRequest) principal() string {
	return strings.TrimSpace(r.Principal)
}

// boundPrincipal returns the principal every ACL binding is made over, DERIVED from the
// subscriber identifier.
func (r SubscriberProvisioningRequest) boundPrincipal() string {
	if derived, err := model.CanonicalKafkaPrincipal(strings.TrimSpace(r.SubscriberID)); err == nil {
		return derived
	}

	return r.principal()
}

// consumerGroupPrefix returns the PREFIXED ACL resource name for this subscriber's
// consumer group namespace, DERIVED from its identifier.
func (r SubscriberProvisioningRequest) consumerGroupPrefix() string {
	if strings.TrimSpace(r.ConsumerGroupPrefix) == "" {
		return ""
	}

	namespace, err := model.CanonicalConsumerGroupNamespace(strings.TrimSpace(r.SubscriberID))
	if err != nil {
		return ""
	}

	return namespace
}

// host returns the ACL host pattern, defaulting to ACLHostAny.
func (r SubscriberProvisioningRequest) host() string {
	if host := strings.TrimSpace(r.Host); host != "" {
		return host
	}

	return ACLHostAny
}

// iterations returns the PBKDF2 iteration count to use, never below MinScramIterations.
func (r SubscriberProvisioningRequest) iterations() int {
	if r.Iterations <= 0 {
		return DefaultScramIterations
	}

	if r.Iterations < MinScramIterations {
		logrus.WithFields(logrus.Fields{
			"requested": r.Iterations,
			"minimum":   MinScramIterations,
		}).Warn(
			"kafka admin: requested SCRAM iteration count is below the minimum Kafka accepts and is being raised",
		)

		return MinScramIterations
	}

	return r.Iterations
}

// normalizedTopics trims the topic list and drops blanks and duplicates, preserving the
// order the registry recorded.
func (r SubscriberProvisioningRequest) normalizedTopics() []string {
	return normalizeTopicList(r.Topics)
}

// aclEntries builds the exact bindings that constitute the subscriber's access
// boundary.
func (r SubscriberProvisioningRequest) aclEntries() []kafka.ACLEntry {
	principal := kafkaPrincipalPrefix + r.boundPrincipal()
	host := r.host()
	topics := r.normalizedTopics()
	groupPrefix := r.consumerGroupPrefix()

	// The topic operations this grant is made of. Describe is always present; Read is present
	// only when the boundary the row describes is one the broker can keep in full.
	//
	// THE ACCESS MODEL HAS THREE DIMENSIONS AND THIS FUNCTION CAN EXPRESS TWO. A Kafka ACL
	// names a resource type, a resource name, a principal, a host, an operation and a
	// permission; the RECORD KEY is not among them, so no binding constructed here can scope
	// a subscriber to a slice of a topic by key. That is a property of Kafka's authorization
	// model rather than of this client, and no broker configuration changes it.
	//
	// So a key-scoped row gets Describe and NOT Read: the boundary it asks for is one the
	// broker cannot keep, and a credential holding topic Read beside a recorded prefix would
	// read every other ledger's records while the registry described something narrower.
	// Withholding Read leaves the subscriber unable to fetch at all — which is the honest
	// outcome — and issuance separately refuses unless an external key-authorising component
	// is declared and has attested this exact binding.
	//
	// THAT COMPONENT IS NOT IN THIS REPOSITORY. Blnk ships a client for it and nothing else,
	// so record-key isolation is out of product scope; see "Requirement Divergence" in
	// docs/kafka-operations.md, which is the operator-facing statement of it.
	topicOperations := []kafka.ACLOperationType{kafka.ACLOperationTypeDescribe}
	if !r.KeyScoped {
		topicOperations = []kafka.ACLOperationType{
			kafka.ACLOperationTypeRead,
			kafka.ACLOperationTypeDescribe,
		}
	}

	entries := make([]kafka.ACLEntry, 0, len(topics)*len(topicOperations)+1)

	for _, topic := range topics {
		for _, operation := range topicOperations {
			entries = append(entries, kafka.ACLEntry{
				ResourceType:        kafka.ResourceTypeTopic,
				ResourceName:        topic,
				ResourcePatternType: kafka.PatternTypeLiteral,
				Principal:           principal,
				Host:                host,
				Operation:           operation,
				PermissionType:      kafka.ACLPermissionTypeAllow,
			})
		}
	}

	if groupPrefix != "" {
		entries = append(entries, kafka.ACLEntry{
			ResourceType:        kafka.ResourceTypeGroup,
			ResourceName:        groupPrefix,
			ResourcePatternType: kafka.PatternTypePrefixed,
			Principal:           principal,
			Host:                host,
			Operation:           kafka.ACLOperationTypeRead,
			PermissionType:      kafka.ACLPermissionTypeAllow,
		})
	}

	if len(entries) == 0 {
		return nil
	}

	return entries
}

// validateSCRAMPassword enforces the one restriction the SCRAM derivation depends on.
func validateSCRAMPassword(password string) error {
	if password == "" {
		return errors.New("kafka admin: a password is required to provision a SCRAM credential")
	}

	for i := 0; i < len(password); i++ {
		if character := password[i]; character < '!' || character > '~' {
			return errors.New(
				"kafka admin: the SCRAM password contains a character outside printable ASCII (0x21-0x7E). " +
					"SASL preparation would rewrite or reject it, producing a credential that cannot " +
					"authenticate; generate the secret from printable ASCII only",
			)
		}
	}

	if len(password) < MinSCRAMPasswordLength {
		return fmt.Errorf(
			"kafka admin: the SCRAM password is shorter than the %d character minimum. A subscriber "+
				"credential is generated, never chosen, and a Kafka SASL handshake has no rate limit or "+
				"lockout, so a short secret is guessable without restriction",
			MinSCRAMPasswordLength,
		)
	}

	distinct := make(map[byte]struct{}, len(password))
	for i := 0; i < len(password); i++ {
		distinct[password[i]] = struct{}{}
	}

	if len(distinct) < MinSCRAMPasswordDistinctChars {
		return fmt.Errorf(
			"kafka admin: the SCRAM password uses fewer than %d distinct characters, so it is long "+
				"without being unpredictable. Generate it from the printable ASCII alphabet rather than "+
				"padding a shorter value",
			MinSCRAMPasswordDistinctChars,
		)
	}

	return nil
}

// deriveScramUpsertion turns a plaintext password into the salted form the broker
// stores.
func deriveScramUpsertion(principal, password string, iterations int) (kafka.UserScramCredentialsUpsertion, error) {
	salt := make([]byte, scramSaltLength)
	if _, err := rand.Read(salt); err != nil {
		return kafka.UserScramCredentialsUpsertion{}, fmt.Errorf(
			"kafka admin: generating a SCRAM salt for principal %q: %w", principal, err,
		)
	}

	saltedPassword, err := pbkdf2.Key(sha512.New, password, salt, iterations, sha512.Size)
	if err != nil {
		return kafka.UserScramCredentialsUpsertion{}, fmt.Errorf(
			"kafka admin: deriving the %s salted password for principal %q with %d iterations: %w",
			SubscriberSASLMechanism, principal, iterations, err,
		)
	}

	return kafka.UserScramCredentialsUpsertion{
		Name:           principal,
		Mechanism:      kafka.ScramMechanismSha512,
		Iterations:     iterations,
		Salt:           salt,
		SaltedPassword: saltedPassword,
	}, nil
}

// upsertScramCredential sends the credential and interprets the per-user result.
func (a *KafkaAdminClient) upsertScramCredential(
	ctx context.Context,
	upsertion kafka.UserScramCredentialsUpsertion,
) (scramWriteOutcome, error) {
	response, err := a.client.AlterUserScramCredentials(ctx, &kafka.AlterUserScramCredentialsRequest{
		Upsertions: []kafka.UserScramCredentialsUpsertion{upsertion},
	})
	if err != nil {
		// NO ANSWER IS NOT A NO. The request may have reached the broker and been applied
		// with only the reply lost — which is the ordinary shape of a deadline expiring on a
		// contended broker — so the credential may exist. Reported as indeterminate rather
		// than as a failure, because the caller's next decision is whether to compensate, and
		// there is exactly one safe answer when the truth is unknown.
		return scramWriteIndeterminate, fmt.Errorf(
			"kafka admin: writing the %s credential for principal %q: %w",
			SubscriberSASLMechanism, upsertion.Name, err,
		)
	}

	for _, outcome := range response.Results {
		if outcome.User != upsertion.Name {
			continue
		}
		if outcome.Error != nil {
			// THE ONE CASE THAT IS DEFINITELY NOT WRITTEN. The broker answered, about this
			// principal, and refused — so there is nothing at the broker to undo.
			return scramWriteRejected, fmt.Errorf(
				"kafka admin: broker rejected the %s credential for principal %q: %w",
				SubscriberSASLMechanism, upsertion.Name, outcome.Error,
			)
		}

		return scramWriteApplied, nil
	}

	return scramWriteIndeterminate, fmt.Errorf(
		"kafka admin: broker returned no result for principal %q when writing its %s credential, "+
			"so the credential cannot be assumed to exist",
		upsertion.Name, SubscriberSASLMechanism,
	)
}

// scramWriteOutcome says what is known about a credential write, as distinct from
// whether the call succeeded.
//
// The distinction exists because "the call failed" and "nothing was written" are not the
// same statement, and conflating them is silent: a request whose deadline expires while
// AlterUserScramCredentials is in flight sees an error, while the broker has applied the
// credential. Recorded as "not written", that principal can authenticate, is absent from
// the registry, and has no obligation filed against it — so nothing revokes it and
// nothing reports it. Measured on a 300-way concurrent burst before this distinction
// existed: 145 principals left at the broker that no log line, no registry column and no
// settlement sweep knew about, against 18 that were correctly reported.
type scramWriteOutcome int

const (
	// scramWriteApplied means the broker confirmed the write.
	scramWriteApplied scramWriteOutcome = iota

	// scramWriteRejected means the broker answered about this principal and refused, so
	// there is nothing at the broker to undo.
	scramWriteRejected

	// scramWriteIndeterminate means no usable answer arrived, so the credential MAY exist
	// and must be treated as though it does.
	scramWriteIndeterminate
)

// mayHaveReachedTheBroker reports whether a credential could exist as a result of this
// write, which is the only question compensation needs answered.
func (o scramWriteOutcome) mayHaveReachedTheBroker() bool {
	return o == scramWriteApplied || o == scramWriteIndeterminate
}

// CompensateProvisioning undoes the half-completed provisioning a deferred result
// describes.
//
// Parameters:
//   - ctx context.Context: used for its VALUES only; the round trips run on their own
//     bounded deadline, because a deferred compensation's caller is usually holding an
//     expired one.
//   - result SubscriberProvisioningResult: the deferred result, read for the principal
//     and the bindings it attempted.
//
// Returns:
//   - error: nil when nothing was owed or the credential is confirmed revoked; the
//     revocation's error otherwise.
func (a *KafkaAdminClient) CompensateProvisioning(
	ctx context.Context,
	result SubscriberProvisioningResult,
) error {
	if a == nil || !result.CompensationOwed || strings.TrimSpace(result.Principal) == "" {
		return nil
	}

	// FROM THE COMPENSATING RESERVE, never the forward pool. This call runs while the
	// forward queue is at its fullest — that is the condition that produced the work it is
	// undoing — so sharing one pool would make the revocation of an unauthorised credential
	// wait behind the attempts to mint more of them.
	ctx, releasePermit, err := a.admitAdminConversation(ctx, kafkaAdminCompensating)
	if err != nil {
		return err
	}

	defer releasePermit()

	return a.compensateFailedProvisioning(ctx, result.Principal, result.OwedBindings)
}
